### ISSUE TITLE
在Linux环境下有使用xaml与.net 平台开发GUI的方法吗？

### ISSUE THREAD

**Issue by jcyongqin** [geffzhang/opendotnet#1]
张善友老师你好，冒昧的问个问题。
.net core 2.0与xaml标准的发布预示了微软对.net前景的规划。
uwp应用于Windows 10和win phone。
xamarin应用于Mac、iOS与Android。
唯独剩下了Linux。
微软是想使uwp应用于Linux呢，还是等待mono拿出解决方案呢？
我想到的另一个方法是基于本地asp core服务，将xaml转为html由gtk web view呈现。

**Comment by geffzhang** [comment]
xamarin还会覆盖linux
